// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Swift.BBS.Repositories.EfContext;

namespace Swift.BBS.EntityFramework.Migrations
{
    [DbContext(typeof(SwiftCodeBbsContext))]
    partial class SwiftCodeBbsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Swift.BBS.Model.Models.Images", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteFlag")
                        .HasColumnType("int");

                    b.Property<DateTime>("OverdueTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ScanName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScanPic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScanType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScanUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
